sudo: required
language: node_js
node_js:
  - "0.12.2"
before_install:
  - "curl -L http://git.io/ejPSng | /bin/sh"
script:
  - JASMINE_BROWSER=PhantomJS meteor --test --release velocity:METEOR@1.1.0.2_3
